INSERT INTO Topics (Topic_id, Topic_name)
VALUES
(1, 'TOPIC1'),
(2, 'TOPIC2'),
(3, 'TOPIC3');

INSERT INTO Sentences (Sentence_id, Topic_id, Sentence_eng, Sentence_kor, Sentence_level)
VALUES
(1, 1, 'Hello', '안녕하세요', 1),
(2, 2, 'This is a short sentence.', '이것은 짧은 문장입니다.', 2),
(3, 3, 'Learning to code is fun and rewarding.', '코딩을 배우는 것은 재미있고 보람차다.', 3),
(4, 1, 'The quick brown fox jumps over the lazy dog.', '빠른 갈색 여우가 게으른 개를 뛰어넘다.', 4),
(5, 2, 'With great power comes great responsibility.', '큰 힘에는 큰 책임이 따른다.', 5),
(6, 3, 'To be or not to be, that is the question.', '사는 것이냐 죽는 것이냐, 그것이 문제로다.', 6),
(7, 1, 'In a hole in the ground there lived a hobbit.', '땅속 구멍에 호빗이 살았다.', 7),
(8, 2, 'It was the best of times, it was the worst of times.', '최고의 순간이자 최악의 순간이었다.', 8),
(9, 3, 'All human beings are born free and equal in dignity and rights.', '모든 인간은 존엄과 권리에 있어 자유롭고 평등하게 태어났다.', 9),
(10, 1, 'To infinity and beyond!', '무한대와 그 너머로!', 10),
(11, 2, 'Time is money.', '시간은 돈이다.', 1),
(12, 3, 'Practice makes perfect.', '연습이 완벽을 만든다.', 2),
(13, 1, 'Knowledge is power.', '지식은 힘이다.', 3),
(14, 2, 'The early bird catches the worm.', '일찍 일어나는 새가 벌레를 잡는다.', 4),
(15, 3, 'Actions speak louder than words.', '행동이 말보다 더 크게 말한다.', 5),
(16, 1, 'A picture is worth a thousand words.', '한 장의 그림이 천 마디의 말보다 낫다.', 6),
(17, 2, 'Beauty is in the eye of the beholder.', '아름다움은 보는 이의 눈에 있다.', 7),
(18, 3, 'Brevity is the soul of wit.', '간결함은 재치의 영혼이다.', 8),
(19, 1, 'Fortune favors the bold.', '행운은 용감한 자를 돕는다.', 9),
(20, 2, 'The pen is mightier than the sword.', '펜은 칼보다 강하다.', 10),
(21, 3, 'Live and let live.', '살고 살게 하라.', 1),
(22, 1, 'Better late than never.', '늦더라도 안 하는 것보다는 낫다.', 2),
(23, 2, 'All good things must come to an end.', '모든 좋은 일은 끝이 있다.', 3),
(24, 3, 'Absence makes the heart grow fonder.', '부재는 마음을 더 애틋하게 만든다.', 4),
(25, 1, 'A journey of a thousand miles begins with a single step.', '천리 길도 한 걸음부터 시작된다.', 5),
(26, 2, 'All that glitters is not gold.', '반짝인다고 다 금은 아니다.', 6),
(27, 3, 'A watched pot never boils.', '지켜보는 냄비는 끓지 않는다.', 7),
(28, 1, 'Beggars can’t be choosers.', '거지는 선택할 수 없다.', 8),
(29, 2, 'Birds of a feather flock together.', '같은 깃털을 가진 새들은 함께 모인다.', 9),
(30, 3, 'Blood is thicker than water.', '피는 물보다 진하다.', 10),
(31, 1, 'Curiosity killed the cat.', '호기심이 고양이를 죽였다.', 1),
(32, 2, 'Don’t count your chickens before they hatch.', '병아리가 부화하기 전에 닭을 세지 마라.', 2),
(33, 3, 'Don’t put all your eggs in one basket.', '모든 달걀을 한 바구니에 담지 마라.', 3),
(34, 1, 'Early to bed and early to rise makes a man healthy, wealthy, and wise.', '일찍 자고 일찍 일어나는 것은 건강, 부, 지혜를 준다.', 4),
(35, 2, 'Every dog has its day.', '모든 개에게도 그 날이 있다.', 5),
(36, 3, 'Good things come to those who wait.', '좋은 일은 기다리는 자에게 온다.', 6),
(37, 1, 'Honesty is the best policy.', '정직이 최선의 정책이다.', 7),
(38, 2, 'If it ain’t broke, don’t fix it.', '고장 나지 않았다면 고치지 마라.', 8),
(39, 3, 'It takes two to tango.', '탱고는 두 명이 추는 것이다.', 9),
(40, 1, 'Let sleeping dogs lie.', '잠자는 개를 그대로 두어라.', 10),
(41, 2, 'Look before you leap.', '뛰기 전에 잘 살펴라.', 1),
(42, 3, 'Necessity is the mother of invention.', '필요는 발명의 어머니이다.', 2),
(43, 1, 'No man is an island.', '아무도 섬이 아니다.', 3),
(44, 2, 'Out of sight, out of mind.', '보이지 않으면 마음에서도 멀어진다.', 4),
(45, 3, 'Practice what you preach.', '설교한 것을 실천하라.', 5),
(46, 1, 'Rome wasn’t built in a day.', '로마는 하루아침에 이루어진 것이 아니다.', 6),
(47, 2, 'Still waters run deep.', '잔잔한 물이 깊이 흐른다.', 7),
(48, 3, 'The early bird catches the worm.', '일찍 일어나는 새가 벌레를 잡는다.', 8),
(49, 1, 'The grass is always greener on the other side.', '남의 떡이 커 보인다.', 9),
(50, 2, 'The squeaky wheel gets the grease.', '삐걱거리는 바퀴가 기름을 얻는다.', 10),
(51, 3, 'Time heals all wounds.', '시간은 모든 상처를 치유한다.', 1),
(52, 1, 'Too many cooks spoil the broth.', '너무 많은 요리사가 국을 망친다.', 2),
(53, 2, 'Two heads are better than one.', '두 개의 머리가 하나보다 낫다.', 3),
(54, 3, 'When in Rome, do as the Romans do.', '로마에 있을 때는 로마인처럼 행동하라.', 4),
(55, 1, 'You can’t have your cake and eat it too.', '케이크를 먹고 그것을 가지고 있을 수는 없다.', 5),
(56, 2, 'You can’t judge a book by its cover.', '겉모습만 보고 책을 판단할 수 없다.', 6),
(57, 3, 'You reap what you sow.', '뿌린 대로 거둔다.', 7),
(58, 1, 'Actions speak louder than words.', '행동이 말보다 더 크게 말한다.', 8),
(59, 2, 'All that glitters is not gold.', '반짝인다고 다 금은 아니다.', 9),
(60, 3, 'A friend in need is a friend indeed.', '곤경에 처했을 때의 친구가 진정한 친구이다.', 10),
(61, 1, 'A journey of a thousand miles begins with a single step.', '천리 길도 한 걸음부터 시작된다.', 1),
(62, 2, 'A leopard cannot change its spots.', '표범은 그 반점을 바꿀 수 없다.', 2);
